### ISSUE TITLE
市场里的存储库链接

### ISSUE THREAD

**Issue by yfdyh000** [wll8/aar-vsc#1]
https://marketplace.visualstudio.com/items?itemName=xw.aar-vsc
Project Details wll8/aardio_doc 应该改掉，从市场找不到该扩展。

**Comment by wll8** [comment]
ok 这个本来在新版本已经改了， 但新版发不上去，说是带病毒。无奈~~~

![image](https://user-images.githubusercontent.com/28223260/103477641-c1e3e480-4dfb-11eb-9f2a-e1e5e5e8e956.png)

**Comment by yfdyh000** [comment]
> ok 这个本来在新版本已经改了， 但新版发不上去，说是带病毒。无奈~~~
> 
> ![image](https://user-images.githubusercontent.com/28223260/103477641-c1e3e480-4dfb-11eb-9f2a-e1e5e5e8e956.png)

先提交 https://www.microsoft.com/en-us/wdsi/filesubmission?persona=SoftwareDeveloper 解除误报，或许就行了。

**Comment by wll8** [comment]
感谢，我试试。

**Comment by yfdyh000** [comment]
给你发链接时我提交了一份，结果还挺快的：

aar-vsc-1.0.1.vsix
...
Status: Completed
...
Submitted: Jan 3, 2021 下午8:05:57
User Opinion: Incorrect detection
We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

**Comment by wll8** [comment]
还是不行，  可能插件市场没有用 WD .

![image](https://user-images.githubusercontent.com/28223260/103494146-4b34fe80-4e70-11eb-84c8-309a1b77fd0b.png)

![image](https://user-images.githubusercontent.com/28223260/103494437-d1057980-4e71-11eb-9b5c-058515754353.png)
