### ISSUE TITLE
aar.exe

### ISSUE THREAD

**Issue by yfdyh000** [wll8/aar-vsc#2]
`本插件自带 aardio 核心运行环境, 可自行更改.`
应该说明这套环境的获取方法，便于更新和重用。

**Comment by wll8** [comment]
在插件设置中填写 aardio 目录路径，即更改运行环境：

![image](https://user-images.githubusercontent.com/28223260/103477679-14bd9c00-4dfc-11eb-8cbd-1284e58c3bf9.png)


aar.exe 源码即本仓库中 aar.aardio.

**Comment by yfdyh000** [comment]
> 在插件设置中填写 aardio 目录路径，即更改运行环境：
> 
> ![image](https://user-images.githubusercontent.com/28223260/103477679-14bd9c00-4dfc-11eb-8cbd-1284e58c3bf9.png)
> 
> aar.exe 源码即本仓库中 aar.aardio.

原来是个小程序，我说找不到这个环境呢。
想弄个自动化编译，aardio没支持命令行参数的样子，论坛也关闭注册了。
