### ISSUE TITLE
使用扩展时无法自动补全，并且不能运行arrdio文件：Running the contributed command: 'aar.runAll' failed.

### ISSUE THREAD

**Issue by kinderao** [wll8/aar-vsc#3]
看到作者写的这个扩展，非常喜欢，毕竟aardio的ide确实不好用，尝试装上使用aar-vsc，但是在运行aardio文件时，报错：![image](https://user-images.githubusercontent.com/20990642/142979106-7fdeba82-3001-4dc4-b3d9-209d8ac46cb7.png)
`Running the contributed command: 'aar.runAll' failed.`
同时自动补全也没有生效

看了一下作者写的插件原理，是通过aar.exe 来实现aardio的解释器，于是在cmd中直接通过 arr.exe xxx.aardio(目标aardio文件)
还是会报错:
![image](https://user-images.githubusercontent.com/20990642/142980021-b7c2d70a-ca20-4adb-9475-cc37f1febabe.png)

麻烦作者可否帮我看看是什么原因吗
vscode版本信息：
```
Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```
aardio ide版本：v33.36.10

**Comment by wll8** [comment]
你先试试简单的语句能不能运行。因为 aar.exe 里其实用的是 loadCode ，这个函数貌似只支持 aardio 核心库。如果你的代码里的三方库，可能就不能通过 aar.exe 运行了。
