### ISSUE TITLE
运行提示错误：Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by wekylin** [wll8/aar-vsc#4]
装完插件，打开程序代码文件夹，一点运行就提示错误：
Cannot read property 'uri' of undefined

在arrdio ide里运行没问题，还需要什么操作？

**Comment by wll8** [comment]
已在此 [commit](https://github.com/wll8/aar-vsc/commit/2bb7f0e967f11291ce5989e9d1875e5fae2dbd1a) 解决。
